modLoader="javafml"
loaderVersion="[43,)"
license="Not specified"

[[mods]]
modId="emerald_armor"
version="1.0.0"
displayName="Emerald Armor"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.emerald_armor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration