plugins {
    id 'dev.architectury.loom' version '1.11.445'
}

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

loom {
    silentMojangMappingsLicense()
    forge {}
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation project(':common')
}

processResources {
    from project(':common').sourceSets.main.resources
    inputs.properties project.properties
    filesMatching('META-INF/mods.toml') {
        expand project.properties
    }
}
